import uuid

#物理演算・移動関連
GRAVITY = -0.003
JUMP_STRENGTH = 0.12
MOVE_SPEED = 0.1
MOUSE_SENSITIVITY = 0.15

HOUSE_ROOF_SIZE = 20
HOUSE_WALL_HEIGHT = 6
HOUSE_ENTRANCE_WIDTH = 5
HOUSE_ENTRANCE_HEIGHT = 4

TOWER_ROOF_SIZE = 9#タワーの大きさはあまり変えないほうがいいです。
TOWER_WALL_HEIGHT = 20
TOWER_ENTRANCE_WIDTH = 2
TOWER_ENTRANCE_HEIGHT = 4

#ネットワーク
SERVER_IP = "127.0.0.1"
SERVER_PORT = 9999
UPDATE_INTERVAL = 0.1
CLIENT_ID = str(uuid.uuid4())

#銃関連
FIRE_RATE = 0.05
RELOAD_DURATION = 3.0

#プレイヤー
PLAYER_MAX_HP = 100
